# Alap image
FROM node:20.11.1

# Munkakönyvtár beállítása
WORKDIR /app

# Fájlok másolása
COPY . .

# Függőségek telepítése
RUN npm install -g pm2
RUN npm install

# Backend buildelése
RUN npm run build

# Port megnyitása
EXPOSE 3000

# PM2 használata az alkalmazás indításához
CMD ["pm2-runtime", "start", "build/index.js"]
